// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: manager.proto
#ifndef GRPC_manager_2eproto__INCLUDED
#define GRPC_manager_2eproto__INCLUDED

#include "manager.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace manager {

class Manager final {
 public:
  static constexpr char const* service_full_name() {
    return "manager.Manager";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RegisterServer(::grpc::ClientContext* context, const ::manager::RegisterRequest& request, ::manager::RegisterResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::manager::RegisterResponse>> AsyncRegisterServer(::grpc::ClientContext* context, const ::manager::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::manager::RegisterResponse>>(AsyncRegisterServerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::manager::RegisterResponse>> PrepareAsyncRegisterServer(::grpc::ClientContext* context, const ::manager::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::manager::RegisterResponse>>(PrepareAsyncRegisterServerRaw(context, request, cq));
    }
    virtual ::grpc::Status GetClusterInfo(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest& request, ::manager::ClusterInfoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::manager::ClusterInfoResponse>> AsyncGetClusterInfo(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::manager::ClusterInfoResponse>>(AsyncGetClusterInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::manager::ClusterInfoResponse>> PrepareAsyncGetClusterInfo(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::manager::ClusterInfoResponse>>(PrepareAsyncGetClusterInfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RegisterServer(::grpc::ClientContext* context, const ::manager::RegisterRequest* request, ::manager::RegisterResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterServer(::grpc::ClientContext* context, const ::manager::RegisterRequest* request, ::manager::RegisterResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetClusterInfo(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest* request, ::manager::ClusterInfoResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetClusterInfo(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest* request, ::manager::ClusterInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::manager::RegisterResponse>* AsyncRegisterServerRaw(::grpc::ClientContext* context, const ::manager::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::manager::RegisterResponse>* PrepareAsyncRegisterServerRaw(::grpc::ClientContext* context, const ::manager::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::manager::ClusterInfoResponse>* AsyncGetClusterInfoRaw(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::manager::ClusterInfoResponse>* PrepareAsyncGetClusterInfoRaw(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RegisterServer(::grpc::ClientContext* context, const ::manager::RegisterRequest& request, ::manager::RegisterResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::manager::RegisterResponse>> AsyncRegisterServer(::grpc::ClientContext* context, const ::manager::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::manager::RegisterResponse>>(AsyncRegisterServerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::manager::RegisterResponse>> PrepareAsyncRegisterServer(::grpc::ClientContext* context, const ::manager::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::manager::RegisterResponse>>(PrepareAsyncRegisterServerRaw(context, request, cq));
    }
    ::grpc::Status GetClusterInfo(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest& request, ::manager::ClusterInfoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::manager::ClusterInfoResponse>> AsyncGetClusterInfo(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::manager::ClusterInfoResponse>>(AsyncGetClusterInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::manager::ClusterInfoResponse>> PrepareAsyncGetClusterInfo(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::manager::ClusterInfoResponse>>(PrepareAsyncGetClusterInfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RegisterServer(::grpc::ClientContext* context, const ::manager::RegisterRequest* request, ::manager::RegisterResponse* response, std::function<void(::grpc::Status)>) override;
      void RegisterServer(::grpc::ClientContext* context, const ::manager::RegisterRequest* request, ::manager::RegisterResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetClusterInfo(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest* request, ::manager::ClusterInfoResponse* response, std::function<void(::grpc::Status)>) override;
      void GetClusterInfo(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest* request, ::manager::ClusterInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::manager::RegisterResponse>* AsyncRegisterServerRaw(::grpc::ClientContext* context, const ::manager::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::manager::RegisterResponse>* PrepareAsyncRegisterServerRaw(::grpc::ClientContext* context, const ::manager::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::manager::ClusterInfoResponse>* AsyncGetClusterInfoRaw(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::manager::ClusterInfoResponse>* PrepareAsyncGetClusterInfoRaw(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterServer_;
    const ::grpc::internal::RpcMethod rpcmethod_GetClusterInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RegisterServer(::grpc::ServerContext* context, const ::manager::RegisterRequest* request, ::manager::RegisterResponse* response);
    virtual ::grpc::Status GetClusterInfo(::grpc::ServerContext* context, const ::manager::ClusterInfoRequest* request, ::manager::ClusterInfoResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterServer() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RegisterServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterServer(::grpc::ServerContext* /*context*/, const ::manager::RegisterRequest* /*request*/, ::manager::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterServer(::grpc::ServerContext* context, ::manager::RegisterRequest* request, ::grpc::ServerAsyncResponseWriter< ::manager::RegisterResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetClusterInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetClusterInfo() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetClusterInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClusterInfo(::grpc::ServerContext* /*context*/, const ::manager::ClusterInfoRequest* /*request*/, ::manager::ClusterInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetClusterInfo(::grpc::ServerContext* context, ::manager::ClusterInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::manager::ClusterInfoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RegisterServer<WithAsyncMethod_GetClusterInfo<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RegisterServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterServer() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::manager::RegisterRequest, ::manager::RegisterResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::manager::RegisterRequest* request, ::manager::RegisterResponse* response) { return this->RegisterServer(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterServer(
        ::grpc::MessageAllocator< ::manager::RegisterRequest, ::manager::RegisterResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::manager::RegisterRequest, ::manager::RegisterResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterServer(::grpc::ServerContext* /*context*/, const ::manager::RegisterRequest* /*request*/, ::manager::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterServer(
      ::grpc::CallbackServerContext* /*context*/, const ::manager::RegisterRequest* /*request*/, ::manager::RegisterResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetClusterInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetClusterInfo() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::manager::ClusterInfoRequest, ::manager::ClusterInfoResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::manager::ClusterInfoRequest* request, ::manager::ClusterInfoResponse* response) { return this->GetClusterInfo(context, request, response); }));}
    void SetMessageAllocatorFor_GetClusterInfo(
        ::grpc::MessageAllocator< ::manager::ClusterInfoRequest, ::manager::ClusterInfoResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::manager::ClusterInfoRequest, ::manager::ClusterInfoResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetClusterInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClusterInfo(::grpc::ServerContext* /*context*/, const ::manager::ClusterInfoRequest* /*request*/, ::manager::ClusterInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetClusterInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::manager::ClusterInfoRequest* /*request*/, ::manager::ClusterInfoResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RegisterServer<WithCallbackMethod_GetClusterInfo<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RegisterServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterServer() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RegisterServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterServer(::grpc::ServerContext* /*context*/, const ::manager::RegisterRequest* /*request*/, ::manager::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetClusterInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetClusterInfo() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetClusterInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClusterInfo(::grpc::ServerContext* /*context*/, const ::manager::ClusterInfoRequest* /*request*/, ::manager::ClusterInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterServer() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RegisterServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterServer(::grpc::ServerContext* /*context*/, const ::manager::RegisterRequest* /*request*/, ::manager::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterServer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetClusterInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetClusterInfo() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetClusterInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClusterInfo(::grpc::ServerContext* /*context*/, const ::manager::ClusterInfoRequest* /*request*/, ::manager::ClusterInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetClusterInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterServer() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterServer(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterServer(::grpc::ServerContext* /*context*/, const ::manager::RegisterRequest* /*request*/, ::manager::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterServer(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetClusterInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetClusterInfo() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetClusterInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetClusterInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClusterInfo(::grpc::ServerContext* /*context*/, const ::manager::ClusterInfoRequest* /*request*/, ::manager::ClusterInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetClusterInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterServer() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::manager::RegisterRequest, ::manager::RegisterResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::manager::RegisterRequest, ::manager::RegisterResponse>* streamer) {
                       return this->StreamedRegisterServer(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterServer(::grpc::ServerContext* /*context*/, const ::manager::RegisterRequest* /*request*/, ::manager::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterServer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::manager::RegisterRequest,::manager::RegisterResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetClusterInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetClusterInfo() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::manager::ClusterInfoRequest, ::manager::ClusterInfoResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::manager::ClusterInfoRequest, ::manager::ClusterInfoResponse>* streamer) {
                       return this->StreamedGetClusterInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetClusterInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetClusterInfo(::grpc::ServerContext* /*context*/, const ::manager::ClusterInfoRequest* /*request*/, ::manager::ClusterInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetClusterInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::manager::ClusterInfoRequest,::manager::ClusterInfoResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RegisterServer<WithStreamedUnaryMethod_GetClusterInfo<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RegisterServer<WithStreamedUnaryMethod_GetClusterInfo<Service > > StreamedService;
};

}  // namespace manager


#endif  // GRPC_manager_2eproto__INCLUDED
