// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: manager.proto

#include "manager.pb.h"
#include "manager.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace manager {

static const char* Manager_method_names[] = {
  "/manager.Manager/RegisterServer",
  "/manager.Manager/GetClusterInfo",
};

std::unique_ptr< Manager::Stub> Manager::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Manager::Stub> stub(new Manager::Stub(channel, options));
  return stub;
}

Manager::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RegisterServer_(Manager_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetClusterInfo_(Manager_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Manager::Stub::RegisterServer(::grpc::ClientContext* context, const ::manager::RegisterRequest& request, ::manager::RegisterResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::manager::RegisterRequest, ::manager::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterServer_, context, request, response);
}

void Manager::Stub::async::RegisterServer(::grpc::ClientContext* context, const ::manager::RegisterRequest* request, ::manager::RegisterResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::manager::RegisterRequest, ::manager::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterServer_, context, request, response, std::move(f));
}

void Manager::Stub::async::RegisterServer(::grpc::ClientContext* context, const ::manager::RegisterRequest* request, ::manager::RegisterResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterServer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::manager::RegisterResponse>* Manager::Stub::PrepareAsyncRegisterServerRaw(::grpc::ClientContext* context, const ::manager::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::manager::RegisterResponse, ::manager::RegisterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterServer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::manager::RegisterResponse>* Manager::Stub::AsyncRegisterServerRaw(::grpc::ClientContext* context, const ::manager::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterServerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Manager::Stub::GetClusterInfo(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest& request, ::manager::ClusterInfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::manager::ClusterInfoRequest, ::manager::ClusterInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetClusterInfo_, context, request, response);
}

void Manager::Stub::async::GetClusterInfo(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest* request, ::manager::ClusterInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::manager::ClusterInfoRequest, ::manager::ClusterInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetClusterInfo_, context, request, response, std::move(f));
}

void Manager::Stub::async::GetClusterInfo(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest* request, ::manager::ClusterInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetClusterInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::manager::ClusterInfoResponse>* Manager::Stub::PrepareAsyncGetClusterInfoRaw(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::manager::ClusterInfoResponse, ::manager::ClusterInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetClusterInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::manager::ClusterInfoResponse>* Manager::Stub::AsyncGetClusterInfoRaw(::grpc::ClientContext* context, const ::manager::ClusterInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetClusterInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

Manager::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Manager_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Manager::Service, ::manager::RegisterRequest, ::manager::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Manager::Service* service,
             ::grpc::ServerContext* ctx,
             const ::manager::RegisterRequest* req,
             ::manager::RegisterResponse* resp) {
               return service->RegisterServer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Manager_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Manager::Service, ::manager::ClusterInfoRequest, ::manager::ClusterInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Manager::Service* service,
             ::grpc::ServerContext* ctx,
             const ::manager::ClusterInfoRequest* req,
             ::manager::ClusterInfoResponse* resp) {
               return service->GetClusterInfo(ctx, req, resp);
             }, this)));
}

Manager::Service::~Service() {
}

::grpc::Status Manager::Service::RegisterServer(::grpc::ServerContext* context, const ::manager::RegisterRequest* request, ::manager::RegisterResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Manager::Service::GetClusterInfo(::grpc::ServerContext* context, const ::manager::ClusterInfoRequest* request, ::manager::ClusterInfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace manager

