// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: raft.proto

#include "raft.pb.h"
#include "raft.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace raft {

static const char* Raft_method_names[] = {
  "/raft.Raft/RequestVote",
  "/raft.Raft/AppendEntries",
};

std::unique_ptr< Raft::Stub> Raft::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Raft::Stub> stub(new Raft::Stub(channel, options));
  return stub;
}

Raft::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RequestVote_(Raft_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AppendEntries_(Raft_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Raft::Stub::RequestVote(::grpc::ClientContext* context, const ::raft::RequestVoteRequest& request, ::raft::RequestVoteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::raft::RequestVoteRequest, ::raft::RequestVoteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestVote_, context, request, response);
}

void Raft::Stub::async::RequestVote(::grpc::ClientContext* context, const ::raft::RequestVoteRequest* request, ::raft::RequestVoteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::raft::RequestVoteRequest, ::raft::RequestVoteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestVote_, context, request, response, std::move(f));
}

void Raft::Stub::async::RequestVote(::grpc::ClientContext* context, const ::raft::RequestVoteRequest* request, ::raft::RequestVoteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestVote_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::raft::RequestVoteResponse>* Raft::Stub::PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, const ::raft::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::raft::RequestVoteResponse, ::raft::RequestVoteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestVote_, context, request);
}

::grpc::ClientAsyncResponseReader< ::raft::RequestVoteResponse>* Raft::Stub::AsyncRequestVoteRaw(::grpc::ClientContext* context, const ::raft::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestVoteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Raft::Stub::AppendEntries(::grpc::ClientContext* context, const ::raft::AppendEntriesRequest& request, ::raft::AppendEntriesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::raft::AppendEntriesRequest, ::raft::AppendEntriesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AppendEntries_, context, request, response);
}

void Raft::Stub::async::AppendEntries(::grpc::ClientContext* context, const ::raft::AppendEntriesRequest* request, ::raft::AppendEntriesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::raft::AppendEntriesRequest, ::raft::AppendEntriesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AppendEntries_, context, request, response, std::move(f));
}

void Raft::Stub::async::AppendEntries(::grpc::ClientContext* context, const ::raft::AppendEntriesRequest* request, ::raft::AppendEntriesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AppendEntries_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::raft::AppendEntriesResponse>* Raft::Stub::PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::raft::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::raft::AppendEntriesResponse, ::raft::AppendEntriesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AppendEntries_, context, request);
}

::grpc::ClientAsyncResponseReader< ::raft::AppendEntriesResponse>* Raft::Stub::AsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::raft::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAppendEntriesRaw(context, request, cq);
  result->StartCall();
  return result;
}

Raft::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Raft_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Raft::Service, ::raft::RequestVoteRequest, ::raft::RequestVoteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Raft::Service* service,
             ::grpc::ServerContext* ctx,
             const ::raft::RequestVoteRequest* req,
             ::raft::RequestVoteResponse* resp) {
               return service->RequestVote(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Raft_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Raft::Service, ::raft::AppendEntriesRequest, ::raft::AppendEntriesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Raft::Service* service,
             ::grpc::ServerContext* ctx,
             const ::raft::AppendEntriesRequest* req,
             ::raft::AppendEntriesResponse* resp) {
               return service->AppendEntries(ctx, req, resp);
             }, this)));
}

Raft::Service::~Service() {
}

::grpc::Status Raft::Service::RequestVote(::grpc::ServerContext* context, const ::raft::RequestVoteRequest* request, ::raft::RequestVoteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Raft::Service::AppendEntries(::grpc::ServerContext* context, const ::raft::AppendEntriesRequest* request, ::raft::AppendEntriesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace raft

